# Generated by Django 4.2.6 on 2023-10-08 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofiletest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfiletest',
        ),
    ]
